LEITMOTIV_VERSION_MAJOR = 0
LEITMOTIV_VERSION_MINOR = 1
LEITMOTIV_VERSION_REVISION = 0


def version_string():
    return '%d.%d.%d' % (LEITMOTIV_VERSION_MAJOR, LEITMOTIV_VERSION_MINOR,
                         LEITMOTIV_VERSION_REVISION)
